version: "3"
services:
  postgres:
    image: postgres:alpine
    container_name: "postgres"
    environment:
      - POSTGRES_DB=tadpgweb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - TZ=GMT
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 6379:6379

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin123
      - MONGO_INITDB_ROOT_PASSWORD=admin123
        volumes:
      - "mongodata:/var/lib/postgresql/data"
    ports:
      - 27017:27017

volumes:
  pgdata:
  mongodata:
