version: "3"
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=tadpgweb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - TZ=GMT
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    volumes:
      - "redisdata:/data"
    ports:
      - 6379:6379

  mongo:
    image: mvertes/alpine-mongo
    volumes:
      - "mongodata:/data/db"
    ports:
      - 27017:27017
volumes:
  mongodata:
  pgdata:
  redisdata:
